cmake_minimum_required(VERSION 3.10)

project(cpp_learning)

add_executable(cpp_learning main.cpp)

add_executable(device_status device_status.cpp Logger.cpp)

add_executable(day03_function day03_function.cpp)

add_executable(day04_vector day04_vector.cpp)

add_executable(day04_device day04_device.cpp)

add_executable(day05_class day05_class.cpp)

add_executable(day06_map day06_map.cpp)

add_executable(day06_devicecharge day06_devicecharge.cpp)

add_executable(day07_file day07_file.cpp)

add_executable(day07_time day07_time.cpp)

add_executable(day07_logger day07_logger.cpp Logger.cpp)

add_executable(day07_logger_practice day07_logger_practice.cpp)

add_executable(day07_csv day07_csv.cpp)

add_executable(day08_review day08_review.cpp Logger.cpp)