cmake_minimum_required(VERSION 3.10)

project(cpp_learning)

add_executable(cpp_learning main.cpp)

add_executable(device_status device_status.cpp)

add_executable(day03_function day03_function.cpp)

add_executable(day04_vector day04_vector.cpp)

add_executable(day04_device day04_device.cpp)

add_executable(day05_class day05_class.cpp)